const VALUE = [
    "Kể ba TƯ THẾ bạn yêu thích nhất hoặc uống",
    "Ai đã từng QUAN HỆ với trên 5  người thì uống",
    "Ai từng hẹn hò trên TINDER thì uống",
    "Nói thầm với đối phương'Tớ muốn ngủ với cậu' hoặc uống",
    "So tay, ai to hơn thì uống",
    "Chơi đấm, đá kéo, người thắng được sai khiến người thua",
    "Trong bát phở của tao luôn có HÀNH, ai không có thì uống",
    "Hôn môi người đối diện hoặc uống",
    "Anh ơi gió lạnh cận kề, bao nhiêu lớp áo thì uống bấy nhiêu ",
    "Kể về lần gần nhất bạn KHÓC hoặc uống",
    "Ai là người chơi hệ HIPHOP thì uống",
    "Uống nếu bạn YÊU đối phương",
    "kể về lý do CHIA TAY gần nhất, hoặc uống",
    "Kể tên loại SEXTOY bạn từng dùng, chưa từng thì uống",
    "Chụp chung một tấm hình hoặc uống",
    "Đoán MÀU SỊP của người đối diện, sai thì uống",
    "Tiết lộ ba điểm bạn thấy QUYẾN RŨ nhất từ đối phương hoặc uống",
    "Ai  còn đầy hơn thì uống",
    "Ai đang yêu xa thì uống",
    "Chụt vào má người bên phải đi nào",
    "Ai đã từng cho CHÓ ĂN CHÈ thì uống nào",
    "Ai đã từng ĐI BÃO thì uống thôi",
    "Uống nếu bạn đang ở trong một mối quan hệ nghiêm túc, số ly bạn uống bằng số năm quen nhau",
    "Ai hay đi muộn nhất thì 2 ly nào",
    "Ai từng say rượu rồi nhắn tin cho nyc thì uống nào",
    "Uống nếu bạn từng crush một người ở đây",
    "Hôn tay người đối diện hoặc uống",
    "Tự kể về  TẬT XẤU của bản thân hoặc uống",
    "Đoán 3 MÓN ĂN yêu thích của người đối diện, đúng 2/3 thì không cần uống",
    "NẮM TAY người đối diện trong 2 phút hoặc uống 2 ly",
    "Ai đang có gấu thì uống đi",
    "Người ai có mực thì uống nào",
    "Các bạn nữ uống đê",
    "Liếm mũi người đối diện hoặc uống",
    "Uống 2 ly đi nào",
    "Ai đã từng xem phim con heo thì uống đê",
    "Show lịch sử web nào, tất cả mọi người",
    "Bạn thấy người đối diện sexy nhất khi nào",
    "Gu bạn trai, gái của bạn là gì",
    "Nụ hôn đầu tiên của bạn là khi nào",
    "Mở shopee, ai nhiều đơn hàng nhất thì uống",
    "Ôm nhau 1 phút hoặc mỗi người uống 1 ly",
    "Liếm mũi người đối diện hoặc uống",
    "Tỏ tình với người đối diện hoặc uống",
    "Nhờ người khác giới cởi một thứ trên người bạn đi nào",
    
]
